### ISSUE TITLE
Dbus.string error

### ISSUE THREAD

**Issue by Viciooso** [Baldomo/asusctltray#21] opened 2023-07-31 18:01 UTC
Traceback (most recent call last):
  File "/home/viciooso/gits/asusctltray/./asusctltray", line 695, in <module>
    TrayIcon(loop)
  File "/home/viciooso/gits/asusctltray/./asusctltray", line 655, in __init__
    self.build_menu()
  File "/home/viciooso/gits/asusctltray/./asusctltray", line 671, in build_menu
    FanCurveController().attach(self.menu)
  File "/home/viciooso/gits/asusctltray/./asusctltray", line 329, in attach
    for item in self.items:
                ^^^^^^^^^^
  File "/home/viciooso/gits/asusctltray/./asusctltray", line 469, in items
    return [FAN_CURVES[i] for i in self.proxy.Profiles()]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/viciooso/gits/asusctltray/./asusctltray", line 469, in <listcomp>
    return [FAN_CURVES[i] for i in self.proxy.Profiles()]
            ~~~~~~~~~~^^^
  File "/home/viciooso/gits/asusctltray/./asusctltray", line 124, in __getitem__
    return self.right[key]
           ~~~~~~~~~~^^^^^
  File "/home/viciooso/gits/asusctltray/./asusctltray", line 80, in __getitem__
    return self._dict[key]
           ~~~~~~~~~~^^^^^
KeyError: dbus.String('Performance')

**Comment by Baldomo** [comment] 2023-08-01 08:33
Duplicate of #20

**Closed by Baldomo** 2023-08-01 08:33 UTC
